### PR TITLE
change: display chat model dropdown to pros only

### PR DESCRIPTION
**Pull request by abeatrix**
CLOSE https://github.com/sourcegraph/cody/issues/1938 https://github.com/sourcegraph/cody/issues/1939 https://github.com/sourcegraph/cody/issues/1940 https://github.com/sourcegraph/cody/issues/1941

This PR addressed the following issues:
- [x] PLG pro users can choose between the supported LLMs for a given chat (but they cannot change LLMs within a single chat)
- [x] PLG free users see that Cody uses Claude 2 for chat by default
- [x] PLG free users see that they need to upgrade to Pro if they'd like to experiment with other supported LLMs
- [x] Enterprise users see the LLM that their admin has chosen for use by Cody but cannot change LLMs.

Changes included:
- Replaced `ChatModelSelection` with new `ChatModelProvider` class
- Pass an object called`UserAccountInfo` into the Dropdown React Component so we can display and disable the model selections accordingly

## Demo

Loom: https://www.loom.com/share/d605b5fc46054696b684ae372f48a236?sid=a46f8156-4148-4adf-8a32-b6472e92f716

## Test plan

Log into Sourcegraph dot com with cody pro enabled:
- The dropdown menu is enabled
- You can choose any of the available LLMs for each chat session

Log into Sourcegraph dot com without cody pro enabled:
- Dropdown menu is disabled
- Hover on the dropdown menu will tells you to upgrade to Cody Pro
image

#### Updated

image

Log into non-DotCom instances:
- Dropdown menu is disabled
- Hover on the dropdown menu will tells you the provider on display is the default chat model on the connected instance
image

#### Updated

image

### Checklist

- [ ] PLG pro users can choose between the supported LLMs for a given chat (but they cannot change LLMs within a single chat)
- [ ] PLG free users see that Cody uses Claude 2 for chat by default
- [ ] PLG free users see that they need to upgrade to Pro if they'd like to experiment with other supported LLMs
- [ ] Enterprise users see the LLM that their admin has chosen for use by Cody but cannot change LLMs.

### CODE REVIEW

**Comment by taylorsperry** [comment]
@abeatrix did you say in the EPD meeting yesterday that you were blocked on design on this?

**Comment by abeatrix** [comment]
> @abeatrix did you say in the EPD meeting yesterday that you were blocked on design on this? I think Tim might have added what you were looking for [here](https://github.com/sourcegraph/cody/issues/1902#issuecomment-1831582049).

@taylorsperry Thanks! @toolmantim Just updated the PR to include the pro badget. Are they supposed to link to somewhere?

**Review by toolmantim — COMMENTED** [review]
Nice @abeatrix! I just cleaned up the flexbox, badge style and added some hover transitions:

https://github.com/sourcegraph/cody/assets/153/88dbb311-724b-4e0c-9d7e-e234caf430d8

When you click the rows that are disabled, can we open up the same link as per the "Upgrade" button? (https://sourcegraph.com/cody/subscription)

**Comment by abeatrix** [comment]
@toolmantim can you also confirm if this also fixed the issue you reported in https://github.com/sourcegraph/cody/issues/2029? It seems to be working for me 🙏 


https://github.com/sourcegraph/cody/assets/68532117/fa31b724-6428-48e7-8247-4964eb9d91d0

**Comment by taylorsperry** [comment]
Beautiful! Thank you @abeatrix and @toolmantim !

**Pull request merged**
