### PR TITLE
Autocomplete: `unstable-openai` provider `legacyModel` conditions

### PR DESCRIPTION
**Pull request by valerybugakov**
- The diff in this PR affects only Cody debug output logs because the model ID is not used by the `unstable-openai` autocomplete provider. I suggest keeping whatever model name clients receive in the Cody output channel for debugging purposes. Open to suggestions 🙂 (cc @slimsag because of your comment [here](https://github.com/sourcegraph/cody/pull/5559#issuecomment-2349595371)).
     - Yes, there might be a deployment name that does not clearly translate to the actual model behind it, but this is still a debugging signal that the client correctly resolved the site configuration. 
     - It makes the code simpler by removing special cases. 
     -  I plan to go over other providers and remove similar conditions there.
- No functional changes.

## Test plan

CI

### CODE REVIEW

**Comment by valerybugakov** [comment]
Going to update failing tests tomorrow 🙂

**Review by arafatkatze — APPROVED** [review]
Valerie Said

>Yes, there might be a deployment name that does not clearly translate to the actual model behind it, but this is still a debugging signal that the client correctly resolved the site configuration.
 

I think that's helpful.

Take this Azure log for example 
```

ChatController: updated authStatus {"authStatus":{"id":"VXNlcjox","hasVerifiedEmail":false,"displayName":null,
"username":"arafatkatze","avatarURL":null,
"primaryEmail":"ara.khan@sourcegraph.com","organizations":{"nodes":[]},

"endpoint":"https://sourcegraph.test:3443/",
"siteVersion":"0.0.0+dev","configOverwrites":{"chatModel":"gpt-4-test","chatModelMaxTokens":7000,

"fastChatModel":"gpt-4-test","fastChatModelMaxTokens":7000,"completionModel":"gpt-35-turbo-instruct-test","completionModelMaxTokens":7000,
"provider":"azure-openai","smartContextWindow":true},"authenticated":true,
"userCanUpgrade":false,"requiresVerifiedEmail":false,"codyApiVersion":2,
"isFireworksTracingEnabled":false},"defaultModelID":"gpt-4-test","currentModelID":"gpt-4-test"}`

```

It has the deployment names and that's better than nothing.

NOTE:  the PR doesn't make any functional changes so I am approving this(I am aware that Valerie needs to fix some testing)

**Comment by valerybugakov** [comment]
TY @arafatkatze. I'll fix the tests and merge this one as is. 

I have a follow-up PR that will add tests for what matters — autocomplete request parameters. Right now, we assert the model ID assigned to the provider instance, but often, it's not used at all to make requests, which means this assertion is irrelevant to the actual functionality.

**Comment by valerybugakov** [comment]
We can also iterate on output logs in follow-up PRs based on the feedback and further testing.

**Comment by valerybugakov** [comment]
Here's the follow up in-progress PR: https://github.com/sourcegraph/cody/pull/5604

**Pull request merged**
