### PR TITLE
Cody: Update workspace server endpoint same as the user settings

### PR DESCRIPTION
**Pull request by deepak2431**
This PR closes [issue](https://github.com/sourcegraph/sourcegraph/issues/54467).
Instead of removing the format URI, which would remove the validation, I have added a function to update the workspace server endpoint settings same as that of the user settings. This way, it won't show any URI error.

## Test plan
All tests have passed.
Tested using different Sign In options such as Cody App, Sourcegraph.com.

### CODE REVIEW

**Comment by deepak2431** [comment]
@abeatrix @philipp-spiess Can I have a review please?

**Comment by deepak2431** [comment]
@abeatrix Thanks for the quick review. Take your time!

That makes sense to me. It would be good to deprecate the server endpoint from the settings. If we have it being used at some places, then it would be better to update that to use the one from the local storage, as maintaining it at two different places can create the possibility of the wrong endpoint being used, which in turn can cause issues to the user while using Cody.

**Review by abeatrix — CHANGES_REQUESTED** [review]
as mentioned previously, we will be deprecating this setting ([PR](https://github.com/sourcegraph/cody/pull/51)).

**Comment by deepak2431** [comment]
@abeatrix As I saw in your PR you have migrated the server endpoint. So, what changes do you want me to make here? Instead of setting it same as the workspace settings, shall I add a migration function for the server endpoint?

**Comment by abeatrix** [comment]
@deepak2431 sorry for the confusion. i believe there is no update needed since the migration function has already been implemented in the new auth flow and since the latest release contain the deprecation message for the serverendpoint setting, we can close this PR if that looks good to you 😄

**Comment by deepak2431** [comment]
@abeatrix No problem. Yeah, I can see the migration function there. Also, I have tested your changes, it looks all good. I will close this PR.

**Pull request closed without merging**
