### PR TITLE
fix symf instanceof CancellationError test flake

### PR DESCRIPTION
**Pull request by sqs**
In unit tests, the `vscode` environment is not fully mocked, so `vscode.CancellationError` is `undefined`. Just use our `AbortError` instead.

Example: https://github.com/sourcegraph/cody/actions/runs/9526461106/job/26261889928?pr=4407#step:9:1806

## Test plan

CI

### CODE REVIEW

**Review by camdencheek — APPROVED** [review]

**Comment by keegancsmith** [comment]
Any idea why this made tests flakey? I would of expected deterministic behaviour when I read this change.

**Comment by olafurpg** [comment]
I took a stab at reverting this PR and implementing support for `CancellationError` in our tests instead https://github.com/sourcegraph/cody/pull/4588

**Comment by olafurpg** [comment]
@keegancsmith A lot of the flaky failures have logs like this
```
window.withProgress: uncaught error EvalError: symf index creation failed: Error: spawn ETXTBSY
    at toSymfError (/home/runner/work/cody/cody/vscode/src/local-context/symf.ts:668:12)
    at SymfRunner._unsafeUpsertIndex (/home/runner/work/cody/cody/vscode/src/local-context/symf.ts:482:19)
```

The stack traces back to conditions related to cancelation. The tests may have become flaky because we are not properly awaiting on things from symf in different places.

**Comment by olafurpg** [comment]
Reverting this PR didn't fix the flaky failure I'm debugging so something else is going on.

**Comment by olafurpg** [comment]
Another attempt: disabling symf altogether in agent integration tests https://github.com/sourcegraph/cody/pull/4591

**Comment by keegancsmith** [comment]
@olafurpg aah ok that makes a lot of sense based on the context on symf not finishing in time being a source of flakiness.

**Pull request merged**
