### PR TITLE
Autocomplete: Fix codebase context inference for embeddings

### LINKED ISSUE #446: Autocomplete only uses available embeddings if cody.codebase is set
Autocomplete uses the [base configuration ](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/configuration.ts?L57:9&popover=pinned) which only considers the cody.codebase setting, it does not check the git remote to auto detect the repo if there is no codebase specified.  

The chat context correctly identifies embeddings are available because it replaces the codebase context based on the git remote if there isn’t a cody.codebase setting.  

Steps to reproduce:
Open a repository that has embeddings such as `sourcegraph/cody` but does not have a `.vscode/settings.json` with a `cody.codebase` specified.  
Enable debugging - see that no embeddings events occur

`sourcegraph/sourcegraph` and  `sourcegraph/about` both have `.vscode/settings.json` with the codebase set, removing it will also stop embeddings from happening on autocomplete.

### PR DESCRIPTION
**Pull request by philipp-spiess**
Closes #446

In the current state, embedding results would only ever be added if a `cody.codebase` was configured in the VS Code settings. That was because we didn't account for two things:

- The version of codebase context we passed into the config is the _initial_ version that is only inferred from the config. We have the class `ContextProvider` which is actively tracking changes to the current active document and updates the config accordingly (this is necessary because you can have multiple git repos in a workspace and want to infer the remote from the proper repo)
- Additionally, ContextProvider was only initialized when the chat web view was loaded the first time meaning that context wasn't added if you don't have the sidebar visible (I’m not sure if this affects inline chat too cc @abeatrix @umpox @dominiccooney)

This PR changes the API to accept a `getCodebaseContext` callback that's only queried when the context is actually needed (so it can always resolve to the latest value) and makes sure that `ContextProvider` is initialized as part of the startup.

## Test plan

- Open a repo that is indexed but does not have a codebase config set up (I used `sourcegraph/sourcegraph` but removed the option from the config
- Observe that we now fetch embeddings and that the regular chat still seems to work.

Screenshot 2023-08-01 at 12 43 25
Screenshot 2023-08-01 at 12 42 24

### CODE REVIEW

**Comment by sqs** [comment]
Wow, good catch. I wonder how much this will change things. Kinda worried it will slow stuff down, no?

**Comment by philipp-spiess** [comment]
@sqs It shouldn't slow stuff down because we never wait for the network request (we only fire of an embeddings search and then look if we already have results in the cache synchronously) but I am worried that we start sending less relevant context snippets now because we never rank the embedding results against the local editor ones.

Maybe we land this fix in its own release though so we can better understand the impact 😅

**Comment by chwarwick** [comment]
> Maybe we land this fix in its own release though so we can better understand the impact 😅

When this rolls out do we have the ability to measure if using embeddings has a measurable impact on the acceptance rate?

**Comment by philipp-spiess** [comment]
> When this rolls out do we have the ability to measure if using embeddings has a measurable impact on the acceptance rate?

We do 🙂 https://sourcegraph.looker.com/x/JsYdDYU6kydx4ZkNvyFfKW

**Review by chwarwick — APPROVED** [review]
The changes in this make sense to me, however I also haven't worked much within the extension so I think it would be best to have an additional review from someone more familiar with this codebase.  It would be very beneficial if we could get this into a release soon so that we can measure the potential impact as we have upcoming trials that are specifically looking to measure success based on acceptance rate.

**Comment by philipp-spiess** [comment]
@chwarwick Thanks 🙇 

@umpox / @abeatrix Can I get either of you to glance over this? You've worked on this in the past I think :)

**Review by umpox — APPROVED** [review]
Great catch, thank you!! Double checked inline chat + fixes and all seems as expected.

Side note: This makes me think we should remove the automatically focus Cody on load behaviour for local dev, it doesn't replicate a typical user

**Pull request merged**
