### PR TITLE
feat: support @mention in mid message

### PR DESCRIPTION
**Pull request by abeatrix**
CLOSE https://github.com/sourcegraph/cody/issues/2633

This PR includes changes to support @mention in mid message:
- Add context selection state and input caret tracking
- Add setContextSelection prop to allow parent to update context selection state
- Track inputCaretPosition in state to determine context selection based on caret position
- Store currentChatContextQuery to track context matching query
- Update context selection logic to use caret position rather than full input text
- Pass inputCaretPosition to ChatUITextArea
- Preserve text after caret when selecting context file
- Rename e2e tests for chat:
  - chat.test.ts -> chat-rateLimit.test.ts
  - at-file-context-selecting.test.ts -> chat-atFile.test.ts

mid-at

## Test plan

- Updated existing e2e tests
- Added a new test case for mid-sentence @-file to current e2e test

1. In the chat input box, type "Explain file to me"
2. Move your cursor behind 'Explain file'
3. Add a space behind 'Explain file'
4. Add '@'
5. You should see the file selection window show up

image

image

image

### CODE REVIEW

**Review by toolmantim — COMMENTED** [review]
Woohoo. This is shaping up really nicely!!

Gave it a good test and noticed a few things, which I've tried to highlight in this video:

https://github.com/sourcegraph/cody/assets/153/b32d44f8-163b-4d34-9359-cb0fcc81b807

* Accepting a suggestion should add a space
* Using left and right cursor should hide the suggestion popover
* After accepting a suggestion, hitting backspace and adding a character on the end shouldn't show "No matching files found" (see Slack's implementation for how we should probably handle it)
* Triggered some kind of race condition with editing (perhaps unrelated to this PR)

**Comment by abeatrix** [comment]
@toolmantim thanks for testing this out. Just updated the branch with the following changes, all covered by the updated e2e test as well
- [x] Accepting a suggestion should add a space
- [x] Using left and right cursor should hide the suggestion popover
- [x] After accepting a suggestion, hitting backspace and adding a character on the end shouldn't show "No matching files found" (see Slack's implementation for how we should probably handle it)

**Review by toolmantim — COMMENTED** [review]
Super close! It still shows "No matching files found" (and doesn't dismiss the popover when you send the message)

https://github.com/sourcegraph/cody/assets/153/3a829826-7f6c-49ae-bed9-87547d87fc27

vs

https://github.com/sourcegraph/cody/assets/153/356af8cf-b96e-4543-8a17-250395b9823a

**Review by umpox — APPROVED** [review]
Looks good! Only noticed one small thing:

It seems that the "No matching files found" message doesn't go away when using the arrow keys to go left or right

https://github.com/sourcegraph/cody/assets/9516420/2172f223-2e2f-47be-99c6-366a026a746b

**Comment by abeatrix** [comment]
Thanks for testing the change so thoroughly! I've manually tested it and updated the tests. Please let me know if it is not working correctly for you.

https://github.com/sourcegraph/cody/assets/68532117/a8da765c-82a5-414e-b326-e6278ba55581

**Comment by abeatrix** [comment]
@toolmantim @umpox Thanks for testing the change so thoroughly! I've manually tested it and updated the tests. Please let me know if it is not working correctly for you.

https://github.com/sourcegraph/cody/assets/68532117/a8da765c-82a5-414e-b326-e6278ba55581

**Review by toolmantim — COMMENTED** [review]
For me it still seems to lose the files when you edit the message:

https://github.com/sourcegraph/cody/assets/153/72862c06-c88a-4f9b-9d70-320f060f4c59

And the question mark case is showing "No matching files":

https://github.com/sourcegraph/cody/assets/153/4302751a-0335-425a-b351-92e503bce8d6

**Comment by abeatrix** [comment]
> For me it still seems to lose the files when you edit the message:

That's unrelated to this PR since this PR is for adding @-file in mid-sentence support. Will work on that in my next PR. 

> And the question mark case is showing "No matching files":

Thanks! I will update and make sure to add tests to cover this tomorrow. Surprise the current one doesn't 🫠

**Comment by toolmantim** [comment]
> That's unrelated to this PR since this PR is for adding @-file in mid-sentence support. Will work on that in my next PR.

Ah, I didn't realise sorry! I didn't check main 👍🏼

**Comment by abeatrix** [comment]
> > That's unrelated to this PR since this PR is for adding @-file in mid-sentence support. Will work on that in my next PR.
> 
> Ah, I didn't realise sorry! I didn't check main 👍🏼

np! Just updated the PR with tests too. i think the test should cover all the expected behavior now?

For edits, it should work the same as press UP for history input right? I can look into that next 👍

**Comment by toolmantim** [comment]
🎉

**Pull request merged**
