### PR TITLE
Fix Github SSH URL parsing

### LINKED ISSUE #1572: Cody doesn't parse ssh url with org-id for cloning git repos
**Feedback**
Cody is not able to parse ssh urls when cody.codebase setting is not set explicitly. The remote url is located but not able to parse , here's the error message fom vscode

Cody could not extract repo name from clone URL [org-id@github.com](mailto:org-id@github.com):redacted/redacted.git: TypeError: Invalid URL
at new NodeError (node:internal/errors:387:5)
at URL.onParseError (node:internal/url:564:9)
at new URL (node:internal/url:640:5)
at convertGitCloneURLToCodebaseName

**Customer**
[Customer](https://sourcegraph2020.lightning.force.com/lightning/r/Account/0013t00001xdnmlAAA/view)

[Slack thread](https://sourcegraph.slack.com/archives/C02842Z6YAK/p1691109639814509)

This issue was fixed in PR 567 but [PR 692](https://github.com/sourcegraph/cody/pull/692) removed [these](https://github.com/sourcegraph/cody/pull/567/files/6bf5c166f8ceeec895d0d8b0e124b5e3bf420455#diff-e7c2dcd45c261d1485c51f2963195cc6639c724d4ea9f0e5926c0792836304dc) changes made in [PR 567](https://github.com/sourcegraph/cody/pull/567)

### PR DESCRIPTION
**Pull request by deepak2431**
This PR closes #1572

## Test plan

- Added a test case

### CODE REVIEW

**Comment by deepak2431** [comment]
@philipp-spiess @abeatrix Can I have a review, please?

**Review by abeatrix — APPROVED** [review]

**Comment by deepak2431** [comment]
@abeatrix Can I get this merged, please?

**Comment by abeatrix** [comment]
I approved it and tried to run the tests but it keeps failing the e2e tests. Tagged the team for help

**Comment by deepak2431** [comment]
Cool, thanks @abeatrix!

**Comment by umpox** [comment]
@abeatrix The E2E tests don't correctly run on forks because secrets are not shared. I'll push up these commits on a separate branch so this build can pass, we can still merge these PRs it's just an extra step right now

**Comment by abeatrix** [comment]
> @abeatrix The E2E tests don't correctly run on forks because secrets are not shared. I'll push up these commits on a separate branch so this build can pass, we can still merge these PRs it's just an extra step right now

Oh makes sense, thanks for the help!

**Pull request merged**
