### PR TITLE
VSCode: Update extension metadata

### PR DESCRIPTION
**Pull request by abeatrix**
CLOSE: https://github.com/sourcegraph/cody/issues/3559

- Updated the vs code extension metadata to the ones provided by @iskyOS :
  - Display name: `Cody: AI Coding Assistant with Autocomplete & Chat`
  - Description: `AI coding assistant that understands your codebase. Cody brings autocomplete, chat, and commands to your IDE, helping you generate code, write unit tests, create documentation, and explain complex or legacy code using AI. Choose from several LLMs including GPT-3.5 Turbo, GPT-4 Turbo, and Claude 3, or run local models using Ollama. Cody supports all major languages including JavaScript, TypeScript, Python, Java, Go, and C/C++.`
  - Additional keyword: `code completion` & `ollama`
- Updated vscode/README.md to reflect the updated list of available LLMs for Cody Pro users. 
  - Added new models: Claude 3 Opus, Claude 3 Sonnet, and Claude 3 Haiku, while retaining the existing models such as ChatGPT 3.5 Turbo, ChatGPT 4 Turbo, Claude Instant, and Mixtral.

These updates will provide users with more clarity on what the extension does and expand the options available for LLM selection. The metadata changes will also help better position the extension in the marketplace, making it easier for users to find and understand its benefits.

## Test plan

- Ensure that the README.md renders correctly and all new LLM options are displayed as expected.
- Verify that the extension's display name and description appear correctly in the VS Code marketplace and match the updates made in the package.json.
- Test the extension to confirm no features are affected by this change. All existing tests should pass.
- Notification from Cody should have the updated name:
image

### CODE REVIEW

**Comment by abeatrix** [comment]
I've updated the display name and description based on my discussion with Alex @iskyOS . @toolmantim can we get your input on the design team please? 🙇‍♀️

**Review by iskyOS — APPROVED** [review]
This looks great to me! From my perspective, this will be a great change for helping marketplace searchability (see [this doc](https://docs.google.com/document/d/1Dd6IegY0l7g2x2xBPFKFuEtKw6U0F6uYGAJKTK6AwUQ/edit#heading=h.7g5r2vmzz2jp) for reference).

Would this change have any implications for other places in the extension, or would we need to update anything else to make sure our branding is cohesive @toolmantim ?

**Review by toolmantim — APPROVED** [review]
This new display name should work much better in the product than original version. lgtm 👍🏼

**Review by philipp-spiess — APPROVED** [review]
Niceeee

**Comment by abeatrix** [comment]
Thanks y'all!

**Pull request merged**
