### PR TITLE
fix/context: Resolve project folders to remote repositories in JetBrains

### PR DESCRIPTION
**Pull request by dominiccooney**
Agent does not implement the vscode.git extension. The workspace repo mapper turned off if this extension was absent, causing Enterprise users of JetBrains, etc. to not get remote context search results for their project's current repository. This caused very poor quality, generic chat responses.

This changes the extension to always create the workspace repo mapper. When the vscode.git extension is not available there's a fallback which executes git directly.

Fixes CODY-3839.

## Test plan

Tested manually:

1. Build JetBrains, see sourcegraph/jetbrains CONTRIBUTING.md with `CODY_DIR`, `-PforceAgentBuild=true -PforceCodyBuild=true`.
2. Log into s2 and open a project with a git repository indexed by the remote. Verify that the current repository context chip is a remote one, for example it shows up as `sourcegraph/cody`, and LLM queries produce remote search context.
3. Open a project in a git repository that is not indexed on the remote instance and verify it appears as a local repo, for example, `foo` without a `prefix/`. Note, local repo context appears to be broken in JetBrains (may be Windows-specific) but that is unrelated to this change.
4. Log into a dotcom account and verify that the repository context chip is a local one, for example it shows up as `cody`.

image

## Changelog

- Uses `git` to determine the remote repository from a workspace folder in JetBrains and other non-VSCode IDEs.
- Enterprise JetBrains and other users now get remote context results for their current workspace if it is indexed on the remote.

### CODE REVIEW

**Comment by dominiccooney** [comment]
Hmm, this passes locally so I'm unsure what the problem with the recordings is. Will try to update them on macOS tomorrow.

**Comment by dominiccooney** [comment]
Currently blocked by s2 being broken, I can't update recordings on macOS either.

**Review by abeatrix — APPROVED** [review]
Thank you! The VS team was just talking about this yesterday so this will be super helpful! 

Will test it with VS once this is merged and report back!

**Comment by dominiccooney** [comment]
I'm going to close this, @sqs has a nice simplification that deletes the workspaceRepoMapper entirely, let's land that.

**Pull request closed without merging**
