### PR TITLE
[WIP] Expanding Fixup Ranges by doing intelligent selection

### PR DESCRIPTION
**Pull request by arafatkatze**
Related Issues -> https://github.com/sourcegraph/cody/issues/585 and https://github.com/sourcegraph/cody/issues/223 

## Problem Summary
Currently the selection made by users is not always fully inclusive of the entire range where changes might need to be made by Cody to satisfy the request of fixup by the user. Because we're limiting the changes to only the region that was selected by the user, that creates quite a few problems:
1. Empty Selections don't work( shown by  @sqs ) 
image

2. Variable renaming within a function would miss some parts of the function with the original variable name that wasn't selected
4. Bad selection boundaries cause issues with indentation with the changes are applied coz the diffs function doesn't work perfectly in some edge cases 
5. Refactors -> If you only selected the return value then any refactor would miss other parts of the function where changes need to be applied 
6. Imperfect selection boundaries sometimes lead to repetition of code outside the selection range and sometimes it doesn't generate outputs 
7. Hard mode Problem:  Its hard to do a mega refactor where change request is on a small selection but that edits multiple files and other places in the codebase to make it all work together in synergy. 

## My solution 
I wanted to solve this problem and explore quite a few different ways to be able to solve it.

If we were to not use LLMs then there's three options. 

1. TreeSitter: For TreeSitter, it has different parsers for different languages, and you can probably do the function start, function ending thing with TreeSitter, but I feel that it might be too inconvenient to write and handle a generic code for all these different cases. And then you would also have to import new libraries and stuff. I saw some tree sitter code in issues etc but didn't explore it enough to consider exploring this option.
2. LanguageServerProtocol: even in the LanguageServerProtocol, I'm pretty sure a similar problem is going to persist. I did not explore it deeply enough. 
3. Using some special kind of codegraph tools from SourceGraph, and based on my searches, I was not able to find any special functions that I could potentially use to be able to expand the the range of my code selection. Probably there is something, and if there is something  out there that’s trivial and relatively easier to use, feel free to let me know, but I couldn't find anything in my searches

If we were to use LLms:
The simplest solution was the expand the text selection with prefix suffix and then find all the line numbers of starting/ending of all the functions etc(We can expand this to other cases too like classes interface etc) but for now I wanted to just focus on finding a function within the +-50 lines range. That’s the algorithm I did right now

I am attempting to solve problems 1-5 shown above in the best way that I can by doing an LLM based selection of the closest approximation to a full function for any selection. Sometimes the llm results aren't perfect and in that case this automatically falls back to the original selection without any issues. This is a good first step to solve the problem of automatic range selection. 

### Before

https://github.com/sourcegraph/cody/assets/11155207/53d63ee7-8650-4c03-b935-dfcb64d38c01

### After
https://github.com/sourcegraph/cody/assets/11155207/0bfa817e-9706-49a2-8ee1-14d141c4ca73

## Before 

https://github.com/sourcegraph/cody/assets/11155207/5ab30335-6c2d-4142-849d-47234d6f4100

### After

https://github.com/sourcegraph/cody/assets/11155207/9e06a5ec-9171-476f-b8e2-45172f01280a

NOTE: Some code in this is quite hacky and I am not fully happy about it but I wanted to get something out to show something to people first and then I am happy to cleanup the whole thing to make a proper PR(with feature flags too) if people are okay with my approach.

## Potential Improvements
- I could still do some more prompt engineering to reduce the length of the prompts that I am using and still get results which are just as good as they are right now. This could reduce the token usage of the extra LLM call we are adding
- The extra LLM calls adds a layer of latency I could do some A/B Testing between different LLMs to see which one would be the fastest/cheapest. Something like @abeatrix did [here](https://github.com/sourcegraph/cody/pull/974#issuecomment-1710373050)
- The overwriting in the code structure looks like a bad practice to me and I am happy to fix that to use a much cleaner route so that this code is much more understandable. 
- I only added this to the edit case of fixup but happy to explore if there are perhaps other scenarios of auto selection where something like this can be helpful. Right now I just wanted to show a bare bones example.

Thanks to @abeatrix @jdorfman  I was able to focus on an interesting problem for me to work on. 

## Test plan
Just try this locally and try some ideas that I mentioned in the PR description.

### CODE REVIEW

**Comment by jdorfman** [comment]
@umpox @abeatrix thoughts?

**Comment by arafatkatze** [comment]
@abeatrix i could add your latest changes into this to make a large range fix up selection. Happy to spin up a pr for it. Would you like that?

**Comment by abeatrix** [comment]
> @abeatrix i could add your latest changes into this to make a large range fix up selection(including cases where two functions are selected etc). Happy to spin up a pr for it. Would you like that?

@arafatkatze Sorry about the wait! Yea that'd be great since it's now merged to main, so I'll be happy to review your change once it's merged with the latest update, thank you!

**Comment by arafatkatze** [comment]
@abeatrix There you go -> https://github.com/sourcegraph/cody/pull/1317

**Pull request closed without merging**
