### PR TITLE
remove indirection in vscode webview React components

### PR DESCRIPTION
**Pull request by sqs**
- remove indirection for FileLinkComponent
- remove indirection for ChatModelDropdownMenu
- remove indirection for EditButton
- extract FeedbackButtons and remove indirection
- rm needless ChatButtonComponent (it just wrapped VSCodeButton)

## Test plan

CI

### CODE REVIEW

**Review by abeatrix — COMMENTED** [review]
Not sure if it's related to this PR, but when I build from this branch, the enhanced context window will always show up on both first chat and non-first chat:

https://github.com/sourcegraph/cody/assets/68532117/0b74d286-0c9c-4980-a1ee-2335ec756a0b

**Comment by abeatrix** [comment]
It's *supposed* to show up only when a user has no chat history (fresh install).  I can reproduce on main though so it's not because of the changes in this PR. We can look into it in a follow-up!

**Comment by sqs** [comment]
@abeatrix Ah, thanks for catching that. I can fix that tonight since I just broke it in #3626.

**Review by abeatrix — APPROVED** [review]
Everything works fine for me when testing it manually, except for the enhanced context settings behavior I mentioned above which is unrelated to the changes from this PR 
+ the CI is green 👍 
Thanks for cleaning the codebase up 🙇‍♀️

**Pull request merged**
