### PR TITLE
Fix scrollbar for LLM Dropdown in Cody plugin

### LINKED ISSUE #5176: VS Code: Scrollbar is not shown for LLM Dropdown
### Version

v1.30.3

### Describe the bug

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your VS Code editor
2. Login to Cody with Any user
3. Click & Open LLM Dropdown

### Observed behavior:
Scrollbar is not shown for LLM Dropdown

### Expected behavior

Scrollbar should be shown for LLM Dropdown

Scrollbar not available for LLM dropdown

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nirzaf**
Fixes #5176

Add scrollbar to LLM Dropdown in Cody plugin for VS Code.

* **CSS Changes:**
  - Add `overflow-y: auto` to the `.editor` class to ensure vertical scrolling.
  - Add `scrollbar-color: var(--vscode-scrollbarSlider-background) var(--vscode-scrollbarSlider-activeBackground)` to the `.editor` class to style the scrollbar.
  - Retain `scrollbar-width: thin` in the `.editor` class.

please test properly before merge

### CODE REVIEW

**Comment by jdorfman** [comment]
Thanks @nirzaf getting someone on our JetBrains team to take a look.

**Comment by dominiccooney** [comment]
I'm unsure about this one. I have scrollbars (albeit on mac) and the screenshot in the upstream issue seems to show content that simply isn't overflowing—so doesn't need scrollbars.

@jdorfman , you mentioned JetBrains, what's the background on that? The upstream issue is a VSCode one...

**Comment by jdorfman** [comment]
@dominiccooney that was my bad, 🤦 

I meant to ping the VS Code team. Sorry about that!

**Comment by dominiccooney** [comment]
@taiyab is always showing the scrollbar on the llm selector, and these colors, what we want on this component?

**Pull request closed without merging**
