### PR TITLE
Autocomplete: add file name and repeat_penalty for CodeGemma.

### PR DESCRIPTION
**Pull request by zhaoheri**
## Context
- Add the current file name at the beginning of the prompt.
- Explicitly set `repeat_penalty=1.0` for the best performance.

## Test plan
1. Install Ollama https://ollama.com/
2. `ollama pull codegemma:2b` or `ollama pull codegemma:7b`
3. Update user settings:
```
{
  "cody.autocomplete.experimental.ollamaOptions": {
    "url": "http://localhost:11434",
    "model": "codegemma:2b"
  },
  "cody.autocomplete.advanced.provider": "experimental-ollama",
}
```
4. Confirm Cody uses Ollama by looking at the Cody output channel or the autocomplete trace view (in the command palette).

### CODE REVIEW

**Comment by jdorfman** [comment]
Thanks @zhaoheri! I will make sure the right folks see this. :)

**Review by abeatrix — APPROVED** [review]
Will wait for @philipp-spiess for a second pair of eyes but this looks good to me! Thanks for your contribution!

**Review by valerybugakov — APPROVED** [review]
Thanks! LGTM

**Review by philipp-spiess — APPROVED** [review]
Thank you so much!

**Pull request merged**
