### PR TITLE
Improve "explain code" with research and summarization steps

### PR DESCRIPTION
**Pull request by dominiccooney**
This is a first step to making the "explain code high level" recipe more useful. It works by first prompting Cody to think and research, then summarize. This produces more organized explanations, usually with coherent explanations of the code's purpose.

## Test plan

```
pnpm test:integration
```

Manual test:

- Open some code.
- Cmd-Shift-P, Ask Cody: Explain Code
- Should see successive messages that Cody is reading, then explaining the code.
- In the chat box, `/explain` should trigger the same behavior.

### CODE REVIEW

**Comment by dominiccooney** [comment]
@abeatrix Right now Option-C still does the commands version of this. I see we have arrived at a similar structure for the prompt. Should I merge these?

I think the Option-C one turn version is better at explaining specific selected bits of code, and it is faster.

This new recipe generally seems better than the custom command version over larger files. (Although something about the markdown prompt means it is including more code samples than ever, which I would like to suppress a bit...)

**Review by abeatrix — CHANGES_REQUESTED** [review]
Just built from this branch and noticed the following issues:

- the `/search` command seems broken:
image
- I can run the new explain command from chat and right-click, but the one from the command menu is still linked to the current `/explain`.

**Comment by dominiccooney** [comment]
Ack, I'll take a look at `/search` tomorrow. Thanks for the feedback.

**Comment by abeatrix** [comment]
> I think the Option-C one turn version is better at explaining specific selected bits of code, and it is faster. This new recipe generally seems better than the custom command version over larger files. 

Here is the response from the current /explain command:

image

Here is the response from the new /explain recipe:
image

They seem similar to me, but the current one takes less time to produce.

When I select the whole file and ask Cody to explain using the new recipe, it doesn't seem like it's explaining much in the final response (but i noticed it did pretty well during the thinking step)

image

Here is the response from the current /explain command for comparison.

image


Might be worth sharing with the team to see what they think. Also, should we rename the new recipe to "explain file" instead of "Explain Code" if it does better in explaining larger files? What do you think?

**Comment by dominiccooney** [comment]
Let me close this PR for now, this obviously needs more work.

**Pull request closed without merging**
