### PR TITLE
Chat: Shows welcome message on empty chat only

### PR DESCRIPTION
**Pull request by abeatrix**
CLOSE https://github.com/sourcegraph/cody/issues/2461

image

This PR removes the welcome message after the first question has been submitted.

## Test plan

1. Open a new chat to confirm welcome message is displayed
2. Submit a question / execute a command
3. the welcome message should disappear

## Before

image

### CODE REVIEW

**Review by kalanchan — APPROVED** [review]
gooo!

**Comment by toolmantim** [comment]
The original intention of the linked issue was that if you start a new chat you don’t get the welcome message. Did we try that and it didn’t feel right, or?

**Comment by abeatrix** [comment]
That's the behavior in this PR, isn't it? You don't see a welcome message after you have started a new chat? Or did I misinterpret the issue lol?

**Comment by toolmantim** [comment]
I don’t love it just disappearing. If we feel it’s too blank to simply exclude any welcome message, we can instead have a more minimal welcome message for chats that aren’t the very first one.

**Comment by toolmantim** [comment]
Ah! So the original issues was meant to be:
- On your first chat, it has the welcome message
- Any additional chats you start don’t show the welcome message at all

**Comment by abeatrix** [comment]
Some clarify questions:

By chat are you referring to chat message, or chat panel? 

> * Any additional chats you start don’t show the welcome message at all

Don't show the welcome message forever?

**Comment by toolmantim** [comment]
> By chat are you referring to chat message, or chat panel?

Whole chats (chat panels)

> Don't show the welcome message forever?

Yep, only on the first chat they ever create.

We can try it out in a PR and see how it feels, and if it feels too bare maybe we need a more minimal chat welcome message for chats after the first one.

**Comment by sqs** [comment]
Love this change! Feels so much cleaner. Found and fixed a minor bug: https://github.com/sourcegraph/cody/pull/3354.

**Pull request merged**
