### PR TITLE
vscode: remove warning for vite CJS deprecation in builds

### PR DESCRIPTION
**Pull request by keegancsmith**
This warning was bothering me and was pretty easy to resolve. I believe our project needs to remain CJS for vscode extensions, so instead we can just opt in to modules via the mts filename on vite's config.

  The CJS build of Vite's Node API is deprecated. See
  https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated
  for more details.

Test Plan: ran "pnpm build" in vscode and did not get the above warning.

### CODE REVIEW

**Comment by keegancsmith** [comment]
Can someone explain how this breakage is related to my PR? I retried the build and it failed in the same way:

```
TypeError: Right-hand side of 'instanceof' is not an object
    at IndexManager.forceRefreshIndex (/home/runner/work/cody/cody/vscode/src/local-context/symf.ts:837:19)
    at Object.callback (/home/runner/work/cody/cody/vscode/src/local-context/symf.ts:694:13)
    at <anonymous> (/home/runner/work/cody/cody/agent/src/agent.ts:743:13)
    at <anonymous> (/home/runner/work/cody/cody/vscode/src/jsonrpc/jsonrpc.ts:98:21)
 ❯ IndexManager.forceRefreshIndex ../vscode/src/local-context/symf.ts:837:19
    835|             })
    836|         } catch (error) {
    837|             if (!(error instanceof vscode.CancellationError)) {
       |                   ^
```

vscode.CancellationError is a class and people do this check all over the place: https://sourcegraph.com/search?q=context:global+%22instanceof+vscode.CancellationError%22+or+%22instanceof+CancellationError%22&patternType=keyword&sm=0

Is this a weird interaction between CJS and ESM? Either way gonna retry the build and maybe I'll be third try lucky.

**Comment by keegancsmith** [comment]
Ok on the third try the test passes. Super weird flake.

**Comment by abeatrix** [comment]
@jamesmcnamara just saw you are not on the vs code group so added you manually 😄 
@kalanchan can you add James to the VS code group / unify the client group please 🙇‍♀️

**Comment by jamesmcnamara** [comment]
@abeatrix thanks!

**Review by jamesmcnamara — APPROVED** [review]
LGTM. That was bugging me too

**Comment by sqs** [comment]
@keegancsmith In unit tests, the `vscode` environment is not fully mocked, so `vscode.CancellationError` is `undefined`. 

https://github.com/sourcegraph/cody/pull/4574

**Pull request merged**
