### PR TITLE
CLI: add `auth` subcommand

### PR DESCRIPTION
**Pull request by olafurpg**
Fixes CODY-2633

Previously, users had to set the environment variables `SRC_ACCESS_TOKEN` and `SRC_ENDPOINT` to authenticate with the [Cody CLI](https://community.sourcegraph.com/t/feedback-on-cody-cli-experimental-feature/78). Now, users can use the `cody auth login --web` command instead.

```sh
cody auth login --web
cody auth logout
cody auth accounts
```

The `login --web` command allows users to authenticate through the browser instead. The non-secret configuration settings (username and server endpoint) are stored in a JSON file in the users Cody "config directory", and the access token is stored in the operating systems secret storage (Keychain on macOS, Secret Service API/libsecret on Linux, and Credential Vault on Windows).

Implementation note: from past experience, I decided to implement multi-account support from the start. Most casual users don't need this functionality but it's super convenient for internal testing and it's not much more effort compared to only supporting a single account.

## Test plan

Manually tested these flows:

```
# Without SRC_ACCESS_TOKEN
cody auth login # errors
cody auth login --web # browser redirect works
cody auth login --web # already logged in
cody auth login # already logged in
cody auth login # prints current account
cody auth accounts # lists one account
cody auth logout # logs out
cody auth logout # errors, already logged out

# With SRC_ACCESS
cody auth login # Success, uses token
cody auth login # In separate terminal without SRC_ACCESS_TOKEN, works
```

### CODE REVIEW

**Comment by olafurpg** [comment]
The failing Windows check is unrelated to this PR 
```
 FAIL  |agent| src/chat-response-quality.test.ts [ agent/src/chat-response-quality.test.ts ]
Error: Command failed: pnpm run build:agent
 ❯ checkExecSyncError ../node:child_process:890:11
 ❯ Proxy.execSync ../node:child_process:962:15
 ❯ buildAgentBinary src/TestClient.ts:103:5
    101|     //

    102|     //   pnpm test agent/src/index.test.ts
```

**Review by sqs — APPROVED** [review]
It broke for me initially:

```
~/src/github.com/sourcegraph/cody$ p -C agent run agent auth login --web

> @sourcegraph/cody-agent@0.0.5b agent /Users/sqs/src/github.com/sourcegraph/cody/agent
> pnpm run build && node --enable-source-maps dist/index.js "auth" "login" "--web"


> @sourcegraph/cody-agent@0.0.5b build /Users/sqs/src/github.com/sourcegraph/cody/agent
> pnpm run -s build:root && pnpm run -s build:agent

✖ ENOENT: no such file or directory, open '/Users/sqs/Library/Preferences/Cody-nodejs/user-settings.json' Error: ENOENT: no such file or directory, open '/Users/sqs/Library/Preferences/Cody-nodejs/user-settings.json'
    at Object.openSync (node:fs:593:3)
    at Object.writeFileSync (node:fs:2325:35)
    at writeUserSettings (/Users/sqs/src/github.com/sourcegraph/cody/agent/src/cli/auth/settings.ts:31:8)
    at loginAction (/Users/sqs/src/github.com/sourcegraph/cody/agent/src/cli/auth/command-login.ts:120:5)
    at _Command.<anonymous> (/Users/sqs/src/github.com/sourcegraph/cody/agent/src/cli/auth/command-login.ts:53:29)
    at _Command.parseAsync (/Users/sqs/src/github.com/sourcegraph/cody/node_modules/.pnpm/commander@11.1.0/node_modules/commander/lib/command.js:936:5)
```

mkdir'ing that dir fixed it.

I was surprised that it signed me in automatically, though! It didn't show me an auth screen in my browser:

```
$ p -C agent run agent auth login --web           

> @sourcegraph/cody-agent@0.0.5b agent /Users/sqs/src/github.com/sourcegraph/cody/agent
> pnpm run build && node --enable-source-maps dist/index.js "auth" "login" "--web"


> @sourcegraph/cody-agent@0.0.5b build /Users/sqs/src/github.com/sourcegraph/cody/agent
> pnpm run -s build:root && pnpm run -s build:agent

✔ Authenticated as sqs at Sourcegraph endpoint https://sourcegraph.sourcegraph.com
```

I would have expected it to ask me which Sourcegraph instance to auth to. I realize I had `SRC_ENDPOINT` set in my env in that shell session for some reason, so maybe this is an edge case and I would have figured that out. Anyway, stream of consciousness comment, I think this is fine.

Annnd...the chat worked!

**Comment by olafurpg** [comment]
> mkdir'ing that dir fixed it.

Fixes!

> I was surprised that it signed me in automatically, though! It didn't show me an auth screen in my browser:

Good point. I added a confirmation dialog when both --web and --access-token (`SRC_ACCESS_TOKEN`) are present.
CleanShot 2024-06-28 at 16 22 31@2x

**Comment by olafurpg** [comment]
The Windows CI failure is suspicious because it has failed consistently on every check in this PR and I haven't seen this failure in other CI jobs on `main`. I don't understand why it always fails on agent/src/chat-response-quality.test.ts 🤔 will wait with merging until I get all the checks green

**Comment by jtibshirani** [comment]
>  I don't understand why it always fails on agent/src/chat-response-quality.test.ts 

I haven't reviewed this PR carefully, but just chiming in to say -- we should delete this test! It is fragile, and it's fully superseded by the Chat questions in `cody-leaderboard`.

**Comment by olafurpg** [comment]
I'll try that and see if it helps. Thank you for chiming in!

**Pull request merged**
