### PR TITLE
Autocomplete: Use IDE code navigation for context

### PR DESCRIPTION
**Pull request by philipp-spiess**
Screenshot 2023-07-31 at 13 27 31
Screenshot 2023-07-31 at 13 26 18

### CODE REVIEW

**Comment by vovakulikov** [comment]
Hmm, this is an interesting idea. I suspect that this PR isn't fully ready yet to be merged, but I think this is smart. I'm curios though what will happen with languages that VSCode doesn't have a built-in lang server support for? But I don't see this is as a blocker since the code nav just extends the Jaccard algorithm.

**Comment by sqs** [comment]
@efritz hacked on this today and got it to work pretty nicely in a demo! See the `ef/enhanced-completions` branch for his WIP.

**Comment by philipp-spiess** [comment]
See https://github.com/sourcegraph/cody/pull/472 for what happens when smarter people take a look at this 🤯

**Comment by efritz** [comment]
> See https://github.com/sourcegraph/cody/pull/472 for what happens when smarter people take a look at this 🤯 

I had to plagiarize you so hard to get started though.

Then I spent four hours debugging a == that should've been a !=.

**Comment by philipp-spiess** [comment]
Superset by these plans: https://docs.google.com/document/d/1XscqkDSsbjutTGX8iVCzoUHrOhiW_VfBuCOjXw8kbK0/edit

**Pull request closed without merging**
