### PR TITLE
Chat: brought back syntax highlighting for most common languages

### PR DESCRIPTION
**Pull request by dominiccooney**
Authored by @ichim-david in #5874. This branch created to run CI.

## Test plan
Ask chat to provide an example program for dart language. 
You should now see the dart snippets having syntax highlighting which started missing after
the work done in this pull request:
https://github.com/sourcegraph/cody/pull/5232

Example screenshot with the fix in action:
dart-syntax

## Changelog
Chat: brought back syntax highlighting for most common languages

### CODE REVIEW

**Comment by ichim-david** [comment]
@dominiccooney my original pull request can also run tests as long as someone approves the latest commit 
pull-request-approval

Pending test running approval, I would rather have my pull request only where I've written a few comments where I've asked for input which I am still waiting for rather than having this copy.
Regardless thanks for bringing awareness to it and testing it today.

**Comment by dominiccooney** [comment]
@ichim-david yes, I have been hitting the approval button, but there's some tests which fetch a token and additionally need to be run from a branch in the sourcegraph repo, unfortunately.

**Review by beyang — APPROVED** [review]

**Comment by beyang** [comment]
@sqs we previously switched from highlight.js to lowlight in https://github.com/sourcegraph/cody/pull/4268

I tested the behavior added in that PR (ability to select text while response is still streaming) and found no regression in this PR. Lmk if you recall additional context that should cause us to prefer lowlight to highlight.js for syntax highlighting (that would necessitate reverting this PR).

**Comment by ichim-david** [comment]
@beyang lowlight does what I did https://github.com/wooorm/lowlight/blob/main/lib/common.js which was to import directly the languages.
The only use of lowlight was to import the common object https://github.com/sourcegraph/cody/pull/5953/files#diff-1c65191a2bd288ddd01bba07bfb76e01e8b0187c6556f2fab1886c58ffc7781fL2
which I've recreated here https://github.com/sourcegraph/cody/pull/5953/files#diff-29f8a901ba5213aedf75195f2cd5da814927503f49be89f005149cb3be57f219R56
alongside the extra languages I've seen in the previous list plus what @dominiccooney mentioned as something common.

Initially, I wanted to continue to use lowlight however due to the different pins and after receiving a good comment from @vovakulikov I've dropped it entirely https://github.com/sourcegraph/cody/pull/5874#discussion_r1797268755

These are the kind of feedback that we need from you guys as we have no way of knowing some of the decisions involved in certain versions used and I was grateful to receive it.
As such I consider this a good fix although I am curious about what @sqs has to say about it :)

**Comment by beyang** [comment]
thanks for the context—and the contribution—this is super helpful!

**Pull request merged**
