### PR TITLE
Intelligent Cody: Fetch locations multiple hops in the graph

### PR DESCRIPTION
**Pull request by efritz**
This PR modifies the initial implementation in #692 to not only track definitions _within the current user selection_, but also _definitions of symbols referenced in fetched definitions_. This goes two hops deep in the code navigation graph, but the implementation is general enough to go an arbitrary number of hops by updating a `recursionLimit` global variable.

## Test plan

Existing unit tests; validated by hand.

### CODE REVIEW

**Review by abeatrix — COMMENTED** [review]
Cody is stuck when I tried to run this 🤔 
image

**Comment by efritz** [comment]
@abeatrix Looks like maybe definitions are in files that can't be opened in the workspace. What repo/file is this on (I'd like to repro).

In the meantime could you try it on some Go or TypeScript code? I'm currently testing on the sg/sg repo so I might be blind to some issues in Python code or non-sg repositories at the moment.

**Comment by abeatrix** [comment]
@efritz sounds good, will try it on go and typescript and report back! Here is the repo with the code I highlighted when running into the aforementioned issue: https://sourcegraph.com/github.com/langchain-ai/langchain/-/blob/libs/langchain/langchain/prompts/prompt.py?L57-92

**Comment by abeatrix** [comment]
python: 
image
typescript:
image
go:
image

Should we limit the amount of symbol we include in each request? I'm getting ` WARN [mainThreadStorage] large extension state detected (extensionId: sourcegraph.cody-ai, global: true): 12056.3720703125kb. Consider to use 'storageUri' or 'globalStorageUri' to store this data on disk instead.` 😅 

It also seems to look for symbols from files beyond the current workspace 👀 
image

**Comment by efritz** [comment]
> Should we limit the amount of symbol we include in each request?

@abeatrix Yes, but I need a way to start to pre-rank the symbols that are most relevant for a given piece of code. I'll be experimenting with that this week as well. It's hard to just say "give me the first 10 symbols" because it will very likely miss critical symbol definitions half-way through a function.

> It also seems to look for symbols from files beyond the current workspace

Yes, otherwise just put your repo/package in the LLM window. This ability is is one part of our differentiation. I do agree it's currently noisy though.

**Review by abeatrix — APPROVED** [review]
approving as the feature is behind an internal feature flag and the plan is to merge this before working on fixes and improvements in the next PR 👍

**Pull request merged**
