### PR TITLE
VS Code: Release 1.20.2

### PR DESCRIPTION
**Pull request by sqs**
## Test plan

CI

### CODE REVIEW

**Comment by RXminuS** [comment]
Any reason we're not including the other fixes?

**Comment by sqs** [comment]
@RXminuS Nope, I just wanted to be conservative. Which other fixes do you think we should include?

**Comment by RXminuS** [comment]
Probably https://github.com/sourcegraph/cody/issues/4348. Should be low risk and was adjacent on a perf thread

**Comment by RXminuS** [comment]
Sorry that was the issue. I mean this one. https://github.com/sourcegraph/cody/pull/4446

**Review by burmudar — APPROVED** [review]

**Review by abeatrix — APPROVED** [review]
Ty!

**Pull request merged**
