### PR TITLE
Update the logged out status bar item with more obvious CTA

### PR DESCRIPTION
**Pull request by toolmantim**
Updates the Cody status bar button to have the text "Sign in to Cody" when not logged in.

[PRD](https://docs.google.com/document/d/1vYkk-LY65k2x0J1AOldbUyxfK_JQCFc3eCUbULZXx70/edit)

[Asana task](https://app.asana.com/0/1206519077296236/1206519077296305)

Before:

https://github.com/sourcegraph/cody/assets/153/a413dfd0-4ad2-4eec-9549-99a17551511e

After:

https://github.com/sourcegraph/cody/assets/153/8d2214f8-1582-4801-b73a-25b4c4cc6451

Events added:

- `CodyVSCodeExtension:signInNotification:shown`
- `CodyVSCodeExtension:signInNotification:signIn:clicked`
- `CodyVSCodeExtension:signInNotification:doNotShow:clicked`
- `CodyVSCodeExtension:statusBarIcon:clicked, { loggedIn: boolean }`

## Test plan

- CI
- Test logged out & logging in
- Test logged in

### CODE REVIEW

**Comment by toolmantim** [comment]
Yep we can update the copy, and I can make it just focus the sidebar.

It does mean the settings quickpick items (links to support/docs) will only be accessible if you’re logged in. I think that’s fine, but just wanted to call it out.

**Comment by chenkc805** [comment]
> It does mean the settings quickpick items (links to support/docs) will only be accessible if you’re logged in. I think that’s fine, but just wanted to call it out.

Yes that's right. Most of the information here is only relevant to logged in users, and if users want to look for docs they can go to Google.
Screenshot 2024-02-21 at 4 25 39 PM

**Comment by toolmantim** [comment]
This PR is ready to go.

@kelsey-brown the final events we ended up logging are slightly different to the Google Doc:

- `CodyVSCodeExtension:signInNotification:shown`
- `CodyVSCodeExtension:signInNotification:signIn:clicked`
- `CodyVSCodeExtension:signInNotification:doNotShow:clicked`
- `CodyVSCodeExtension:statusBarIcon:clicked, { loggedIn: boolean }`

Are these okay? In particular I'm wondering if the `loggedIn` properly on statusBarIcon clicked can be used to identify people clicking the status bar when loggedIn == false.

**Comment by kelsey-brown** [comment]
@toolmantim is CodyVSCodeExtension:signInNotification:shown the enrollment event then? 

> In particular I'm wondering if the loggedIn properly on statusBarIcon clicked can be used to identify people clicking the status bar when loggedIn == false.

Yes, if this is logged with the metadata on the event we can filter/pivot clicks by loggedIn = true / loggedIn = false

**Comment by toolmantim** [comment]
Thanks @kelsey-brown. Yep, that should work as the enrollment event. Though this isn't running as an experiment in the code at all (I've never done that before)

**Review by sqs — COMMENTED** [review]
For the actual text, how about: “(icon) Sign In”? That seems best. Shortest and least words. 

I hate long and advertisingy status bar items. Other competitors (won’t name in public) do this and it looks very spammy. This is not spammy but I want to really be careful to have a super short message down here.

**Comment by toolmantim** [comment]
@sqs I didn't want to confuse it with an Microsoft/GH login button. Are you thinking it's a bad experience for the person that just installed it, or for the person that keeps it installed but doesn't login and wants to ignore it for now (and we don't want them to uninstall)?

**Comment by sqs** [comment]
> @sqs I didn't want to confuse it with a Microsoft/GH login button. Are you thinking it's a bad experience for the person that just installed it, or for the person that keeps it installed but doesn't login and wants to ignore it for now (and we don't want them to uninstall)?

Both. And I just have a negative reaction to anything that takes up a lot of space in my status bar. Can you check with a few other devs on the team for their kneejerk reaction? If I'm the only one, then feel free to disregard.

**Comment by toolmantim** [comment]
First impressions matter! Will straw poll.

**Comment by toolmantim** [comment]
I've updated the label to be "Sign In" so we can unblock this and get it out

**Review by sqs — APPROVED** [review]

**Pull request merged**
