### PR TITLE
VS Code: release v1.6.1

### PR DESCRIPTION
**Pull request by valerybugakov**
- VS Code: release v1.6.1 - patch release.
- Cherry-picked https://github.com/sourcegraph/cody/pull/3283 on top of https://github.com/sourcegraph/cody/commit/88be6f4aac4632301c2d3c361ac60104793e16cd

## Test plan

n/a

### CODE REVIEW

**Review by arafatkatze — APPROVED** [review]

**Review by philipp-spiess — COMMENTED** [review]
These are a lot of changes, should we do them as part of the 1.8 release on Wed instead so we have something to release at all? 😅

**Comment by valerybugakov** [comment]
Would it make sense to do the 1.8 release earlier with this PR? Otherwise, we would need to cherry-pick and release from the branch, which does not have any value in itself. cc @kalanchan @philipp-spiess

**Comment by philipp-spiess** [comment]
@valerybugakov I just know from my side but I do want to get https://github.com/sourcegraph/cody/issues/3216 into the release which is not done yet 😬 . I’m fine with doing a release from `main` personally though.

**Comment by valerybugakov** [comment]
I cherry-picked only the commit I'm interested in for the A/B test on top of the last release to ensure we're good for a Wednesday release.

**Review by philipp-spiess — APPROVED** [review]

**Pull request merged**
