### PR TITLE
backtick

### PR DESCRIPTION
**Pull request by justinmilner1**
Fixes https://github.com/sourcegraph/cody/issues/4909

## Test plan

Screenshot from 2024-07-19 15-57-27

### CODE REVIEW

**Comment by justinmilner1** [comment]
Hey @abeatrix, tiny PR here to fix a ui bug.

**Review by abeatrix — APPROVED** [review]
Ty!!

**Comment by kalanchan** [comment]
Going to close and re-open this to fix the checks

**Comment by kalanchan** [comment]
thanks @justinmilner1 !

**Pull request merged**
