### PR TITLE
import instead of require for web-tree-sitter

### PR DESCRIPTION
**Pull request by sqs**
This bundles to the same code and is more standard.

## Test plan

CI

### CODE REVIEW

**Comment by sqs** [comment]
cc @olafurpg in case you know why it was being require()d

**Review by burmudar — APPROVED** [review]

**Comment by sqs** [comment]
OK, unit tests failing, so I now see why it was done this way. Will find the right fix.

**Comment by olafurpg** [comment]
I haven't worked directly on this part of the codebase so I'm not sure why it's using `require`. Most likely, `web-tree-sitter` performs side effects during initialization that we want to delay. I'm using `require` in the agent entrypoint for similar reasons https://sourcegraph.com/github.com/sourcegraph/cody@d65d7c1a4af11e2c5c4e62b698be81ec236b1573/-/blob/agent/src/index.ts?L14

**Comment by sqs** [comment]
Pretty sure it's a CJS/ESM issue.

**Comment by sqs** [comment]
I found the fix. I am not 100% sure about the root cause, but my suspicion is that vitest's bundling code somehow lets the `Module = Object.assign({}, ...` line at https://sourcegraph.com/github.com/tree-sitter/tree-sitter/-/blob/lib/binding_web/prefix.js reassign the `__vite_ssr_import_N__` var or something.

**Pull request merged**
