### PR TITLE
feat(webviews): add Sourcegraph Teams providers

### PR DESCRIPTION
**Pull request by abeatrix**
CONTEXT: https://sourcegraph.slack.com/archives/C079SAU0E72/p1733964997414119
CLOSE https://linear.app/sourcegraph/issue/CODY-4490/implement-the-upgrade-to-team-upsell-in-the-context-menu

This PR adds new Sourcegraph Teams providers for repositories and directories to the OpenContext menu. These providers are only shown for DotCom users who have the Sourcegraph Teams upgrade feature flag enabled.

The new providers are added with the following URIs:
- `WORKSPACE_DIRECTORY_PROVIDER_URI`
- `WORKSPACE_REPOSITORY_PROVIDER_URI`

Additionally, a new `isRemoteWorkspaceProvider` function is added to the `lib/shared/src/context/openctx/api.ts` file to check if a given provider URI belongs to the Sourcegraph Teams providers.

When a user clicks on a Sourcegraph Teams provider in the OpenContext menu, the corresponding Sourcegraph Teams page will be opened in a new tab.

## Test plan

- Added new Sourcegraph Teams providers for repositories and directories
- Implemented logic to check if a provider is a Sourcegraph Teams provider
- Opened Sourcegraph Teams page in a new tab when a Sourcegraph Teams provider is clicked

Manual testing.

When logged into DotCom and your account has the feature flag enabled:

image

When logged into S2 (enterprise), you should not see the Upgrade to Pro badge:
image

### CODE REVIEW

**Comment by bobheadxi** [comment]
@abeatrix if it's not too big of a lift, I strongly recommend calling all internal references to MT `workspaces` instead of `teams` - "workspace" is the name of the thing, while "teams" is a product-owned name of the _billing plan_ that is highly subject to change. Or, even better, if it can apply to Enterprise as well we should just call it Enterprise.

In this case, the "teams" name is going to be dropped due to a change in direction, and we will no longer be referring to anything as "teams": https://sourcegraph.slack.com/archives/C0814PENH8R/p1733993779559599?thread_ts=1733943118.799079&cid=C0814PENH8R

**Comment by abeatrix** [comment]
> @abeatrix if it's not too big of a lift, I strongly recommend calling all internal references to MT `workspaces` instead of `teams` - "workspace" is the name of the thing, while "teams" is a product-owned name of the _billing plan_ that is highly subject to change. Or, even better, if it can apply to Enterprise as well (most mechanisms should) we should just call it Enterprise. This will make reading the code easier in the future. For displaying product-owned names we should make sure that is somewhat easy to change without a major refactor.
> 
> In this case, the "teams" name is going to be dropped due to a change in direction, and we will no longer be referring to anything as "teams": https://sourcegraph.slack.com/archives/C0814PENH8R/p1733993779559599?thread_ts=1733943118.799079&cid=C0814PENH8R

Does that mean the upsell will be updated to `Upgrade to Workspace`

**Comment by bobheadxi** [comment]
for example, `isSourcegraphTeamsProvider` should be `isWorkspaceProvider`, but any user-facing display text can be the product term instead, which is easy to change

**Comment by abeatrix** [comment]
> for example, `isSourcegraphTeamsProvider` should be `isWorkspaceProvider`, but any user-facing display text can be the product term instead, which is easy to change

@bobheadxi i've renamed them and moved away from using `Teams`.

**Review by eseliger — APPROVED** [review]
Thank you!

**Pull request merged**
