### PR TITLE
Chat: add ability to send editor selection to chat as @-mention

### PR DESCRIPTION
**Pull request by abeatrix**
Follow https://github.com/sourcegraph/cody/pull/3619
Part of https://github.com/sourcegraph/cody/issues/3664

image

This pull request introduces a new feature that allows users to easily share their current editor selection with Cody during a chat conversation. It turns the selection into an @-mention token in their chat inbox.

The following changes have been made:

Add 'cody.chat.context.add' Command:

- A new command 'cody.chat.context.add' has been added to the package.json file, which is registered in the ChatManager class.
- When triggered, this command calls the sendSelectionToChat method in the ChatManager, which retrieves the chat provider and invokes the handleGetUserEditorContext method.

Implement 'sendSelectionToChat' Method:

- The sendSelectionToChat method has been added to the ChatManager class.
- This method retrieves the chat provider and calls the handleGetUserEditorContext method, which is responsible for sending the user's editor selection to the chat.

Update SimpleChatPanelProvider:

- The SimpleChatPanelProvider has been updated to import the ContextItemFile type from the shared codebase context messages.

Update Package.json:

- The package.json file has been updated with the new 'cody.chat.context.add' command configuration, including its category, group, title, icon, and when condition.
- The command has also been added to the context menu and the editor menu group.
- With this feature, users can easily share relevant code snippets or files with the AI assistant during a conversation, providing additional context and improving the quality of the assistant's responses.

## Test plan

Highlight some code and right click and select `Cody Chat: add context`

image

The chat panel should be opened for you with the selection added as an @-mention token

image

If you already have a chat panel opened, it will add it to the end of your input box

## Demo

https://github.com/sourcegraph/cody/assets/68532117/ab2eccba-60a3-463a-aae8-a1c0669c9821

### CODE REVIEW

**Comment by PriNova** [comment]
Nice feature which is very helpful @abeatrix 
Would it be possible to integrate it additionally into the mouse hover popup too?

**Comment by umpox** [comment]
Nice! This means we can [implement the "Add to Chat" ghost text design too.](https://www.figma.com/file/jEsnzgsf0hNuJbqB9pKaGm/VS-Code---Cody---Commands-up-front-and-ChatGPT%2B%2B?type=design&node-id=1161-33280&mode=design&t=GNofSTDZrFNVqenh-0)

Could we do this for both hover and the selection ghost text:
1. If chat is open, show "Add to Chat" instead of "Chat"

**Comment by abeatrix** [comment]
> Nice! This means we can [implement the "Add to Chat" ghost text design too.](https://www.figma.com/file/jEsnzgsf0hNuJbqB9pKaGm/VS-Code---Cody---Commands-up-front-and-ChatGPT%2B%2B?type=design&node-id=1161-33280&mode=design&t=GNofSTDZrFNVqenh-0)
> 
> 
> 
> Could we do this for both hover and the selection ghost text:
> 
> 1. If chat is open, show "Add to Chat" instead of "Chat"

Yea!!! I'll start a follow up for hover and ghost text since this is available to all users and the other ones are for the experiment. Will work on it now!

**Comment by abeatrix** [comment]
> Yea!!! I'll start a follow up for hover and ghost text since this is available to all users and the other ones are for the experiment. Will work on it now!

@umpox here is the follow-up https://github.com/sourcegraph/cody/pull/3732

**Review by kalanchan — COMMENTED** [review]
nice this is awesome! I tested 3 scenarios
1. add editor selection with no chat open, and asking it a question
2. add another editor selection with existing "used" chat open
3. add editor selection with a "new" chat open

Everything works as expected for scenarios 1 & 3 - but everytime I tried to add more editor selection context to an existing used chat(scenario 2), it opens a new chat window. I think this is a bug? It should just add the context to the existing chat - see videos:

Scenario 1:
https://github.com/sourcegraph/cody/assets/51868853/874544c4-fab1-41f7-b1d3-14bc319d9e39

Scenario 2:
https://github.com/sourcegraph/cody/assets/51868853/a7336284-33bb-48ca-8c58-66cf13eb8613

Scenario 3:
https://github.com/sourcegraph/cody/assets/51868853/ea6bdd18-bc68-4cb9-a7aa-29c8b101ab1e

**Comment by abeatrix** [comment]
>  everytime I tried to add more editor selection context to an existing used chat, it opens a new chat window.

Thanks for catching the bug! Can you give the latest commit a try to confirm that fixed the bug?

**Review by kalanchan — APPROVED** [review]

**Comment by kalanchan** [comment]
tbh, this might be even better than @ file, we should do really strong discovery for this

**Comment by PriNova** [comment]
> tbh, this might be even better than @ file, we should do really strong discovery for this

I agree with this. But let it stay for @# and @URL

**Pull request merged**
