### PR TITLE
Chat: Fix "Ask Cody to Explain"

### PR DESCRIPTION
**Pull request by umpox**
## Description

- Pass the correct arguments to the `cody.action.chat` command
- Add type safety to avoid this mistake again

closes https://github.com/sourcegraph/cody/issues/2970

## Test plan

1. Try "Ask Cody to Explain"
2. Check there is no error

### CODE REVIEW

**Comment by vadi2** [comment]
Is there an easy way to test this?

**Comment by umpox** [comment]
@vadi2 If you want to run this locally, you can checkout the branch locally and follow these docs: https://github.com/sourcegraph/cody/blob/main/doc/dev/index.md

**Comment by vadi2** [comment]
> % asdf install
> Install plugins first to be able to install tools

Which plugins should I install?

**Comment by umpox** [comment]
@vadi2 Try this quickstart from the repo root:
`pnpm install && pnpm build && cd vscode && pnpm run dev`

That should work if you have NodeJS installed.

I've added an e2e test for this too

**Comment by vadi2** [comment]
No luck testing it - same issue in the 2nd vscode instance that pops up when I run the `Launch VS Code Extension (Desktop)` task, but it could be that I'm doing something wrong.

**Review by abeatrix — APPROVED** [review]
Confirmed the Ask Cody to Explain works for me:
image


Also updated the failing e2e test that hopefully helps!

**Comment by umpox** [comment]
@vadi2 Might have been an issue with our local flow. We need to do a check on the instructions for first clones.

I've merged this now so will ensure this is included in the next release

**Pull request merged**
